name: CI

on:
  push:
    braches: [ master ]
    
jobs:
  build:
    name: Build all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup JDK
      uses: actions/setup-java@v1
      with:
        java-version: '8' # The JDK version to make available on the path.
        java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
        architecture: x64 # (x64 or x86) - defaults to x64
    - name: Setup SBT and build
      uses: lokkju/github-action-sbt
      with:
        commands: assembly
        sbt_project_directory: ./
