name: Merge master

on:
  push:
    branches:
      - master
    
jobs:
  build:
    name: Build and tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Scala
      uses: olafurpg/setup-scala@v11
      with:
        java-version: "adopt@1.8"    
    - name: Build and Test
      run: sbt +clean +test assembly
